### ISSUE TITLE
Crash while launching my world

### ISSUE THREAD

**Issue by Zack7292** [transfarmer/adventure-items#1]
the name is self talking
crash log: https://paste.dimdev.org/evoqirazos.mccrash

**Comment by nnym** [comment]
Try updating to v1.6.3-beta; I should have fixed it in that version.

**Comment by Zack7292** [comment]
Ok Thx!

**Comment by Zack7292** [comment]
but i had a question, will the sword have a 3D model like in the CQ:R discord, bcs the model is simply awesome and i'll really like to see it with this model

**Comment by nnym** [comment]
That is planned, but I intend to implement the functionality that is most important to gameplay (things like skills and balance) first.
