### ISSUE TITLE
Crash with the pickaxe GUI

### ISSUE THREAD

**Issue by Zack7292** [transfarmer/adventure-items#10]
so, when i try to open the gui with the pickaxe in hand, my game simply crash
https://pastebin.com/cTMYkiU0

**Comment by Zack7292** [comment]
it only happen the 1st time, now i've reload my world and it didn't crash... weird

**Comment by nnym** [comment]
I also experienced this bug. I fixed it, but I will release the fix later.

**Comment by Zack7292** [comment]
ok
