### ISSUE TITLE
Crash while looking at the combat section

### ISSUE THREAD

**Issue by Zack7292** [transfarmer/adventure-items#11]
i was looking at the combat section, and this crash happen: https://paste.dimdev.org/rofogulemu.mccrash

**Comment by nnym** [comment]
I cannot reproduce it. Could you give me more information? Do you have other mods that extend tooltips? If so and this occurs not only for soulbound weapons, then could you send me a screenshot of a toolip without soulbound armory?

**Comment by Zack7292** [comment]
yes i do have other mods, also i have another issue, so ima give you the link of both the issue and the pack:
crash log (i only die in survival by a silverfish in a stronghold but i'm not sure of it is what cause it): https://paste.dimdev.org/kubuyamifu.mccrash

modpack (use last forge version): http://www.mediafire.com/file/h6y7u5ltz2zzkxm/Infex_V.0.0.007c.zip/file

**Comment by Zack7292** [comment]
and for the tooltip, the only mod i could see doing this is smooth font, but otherwise its in-game (not in creative tab) tooltip, so i don't see why it will occur in this precise tab

**Comment by nnym** [comment]
I am unable to reproduce the bugs. Could you try to reproduce them with the least amount of mods necessary? Also, the version of soulbound armory in the modpack that you sent me is 2.6.2 and currently the latest is 2.6.3.

**Comment by Zack7292** [comment]
yea, I've seen it but it, but ima give you a new link with videos when i got time

**Comment by Zack7292** [comment]
i can't seem to be able to reproduce the 1st one, but i reproduce the second and find a third one (but the third is not an actual crash)

2nd crash (video): https://youtu.be/26O2e7iNUps  (i've also find out that sometime this crash can make your world crash each time you try loading it)

the bug video: https://youtu.be/V32sE2sBxJg

(they've been tested in a new world just to be sure)

the modpack (updated to the latest of every mods :) ) : https://www.mediafire.com/file/c3zr7wvu7xm69sy/InfEx_V.0.0.007d.zip/file

**Comment by nnym** [comment]
Thank you. I accidentally fixed the bug that causes the crash earlier. Also, I recommend that in the future, when you open issues, you state the only mods that need to be installed in order to reproduce them as it makes fixing bugs faster, because some core mods do not work in development environments.
