### ISSUE TITLE
Causes forestry backpacks to no longer auto pickup relevant items.

### ISSUE THREAD

**Issue by slidedrum** [transfarmer/adventure-items#14]
When using [Forestry](https://www.curseforge.com/minecraft/mc-mods/forestry) backpacks (Tested with digging backpack) they are supposed to automatically put relevant items inside them when picked up.  (In digging backpack's case dirt and stone blocks.)  However when Soulbound armory is installed, it no longer automatically places items into the backpack.  You can still place them inside manually. 

Tested with the latest version of Forestry (forestry_1.12.2-5.8.2.409)
and the latest version of Soulbound Armory (soulboundarmory-2.6.2) and an older version (soulboundarmory-2.5.1)  Issue persists on both.

Have isolated the issue to this mod.  Can reproduce 100% of the time when only installing these two mods.   Giving myself a digging backpack, and picking up dirt.  Goes into your inventory, not into the backpack.  

Not sure if it has any useful info, but here is my [latest.log](https://github.com/transfarmer/soulbound-armory/files/4476946/latest.log) Loaded up a world where I already had a digging backpack, and mined a couple blocks of dirt.  Then quit the game.

I am not aware of any other issues, but it may affect other mods that do things when you pick up items.  Any chance of this getting fixed?  

Thank you!

**Comment by nnym** [comment]
This issue is most likely caused my item pickup handler in order for bound slots to work and (optionally) for items to be added to offhand when main inventory is full. I will see what I can do about it.
