### ISSUE TITLE
Causes server to crash on startup.

### ISSUE THREAD

**Issue by slidedrum** [transfarmer/adventure-items#2]
**Describe the bug**
Server crashes on startup.

**To Reproduce**
Install on server.
Start server
"Encoutnered an unexpected exception java.lang.NoSuchFieldError: XP_BAR"

**Expected behavior**
You know, not crash on startup.

**Versions**
CQR: 1.8.0A
Soulweapons: 1.6.4-beta
ilibrary: 1.7.19
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report: [crash-2020-02-08_00.56.25-server.txt](https://github.com/transfarmer/soul-weapons/files/4173837/crash-2020-02-08_00.56.25-server.txt)

Log file: [latest.log](https://github.com/transfarmer/soul-weapons/files/4173838/latest.log)

Singleplayer/Multiplayer: Multiplayer, server only.  Client seems to start with no issues.
Other mods (that are necessary to produce the bug): Isolated to just Chocolate Quest Re-poured requirements.
Other mods (that are also installed): CQR, Ilibrary

**Comment by nnym** [comment]
My bad: I should have tested it on a server. I posted a fix on CurseForge.
