### ISSUE TITLE
Using the 1.15.2 Version

### ISSUE THREAD

**Issue by Madgadget** [transfarmer/adventure-items#20]
Hello again, I am new to using github so I currently have no clue as to how to use the 1.15.2 version/ make it into a .jar so I can use it in my worlds. Can you please help me? Thank you!

**Comment by nnym** [comment]
No can do.

The standard procedure for building mods from GitHub is cloning a branch and running `./gradlew build` in it:
```sh
git clone git@github.com:auoeke/soulbound-armory -b 1.15.2 # Clone branch 1.15.2.
cd soulbound-armory
./gradlew build
# Result is build/libs/soulbound-armory-<version>.jar.
```
I tried to build it but that version of soulbound armory has dependencies that are no longer available. Besides, I had rewritten much of the codebase so it was very buggy and not very useful.
