### ISSUE TITLE
Unable to hit anything.

### ISSUE THREAD

**Issue by slidedrum** [transfarmer/adventure-items#3]
**Describe the bug**
Can't damage any entities.

**To Reproduce**
Install mod.  Punch something.

**Expected behavior**
I expect the mob to take damage.

**Versions**
Soulwepons: 1.6.6
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Singleplayer/Multiplayer: Both
Other mods (that are necessary to produce the bug): None
Other mods (that are also installed): None

**Comment by nnym** [comment]
I'm currently testing a new version and I seem to be able to hit entities. I'll post an update to CurseForge soon. Meanwhile, do you see anything unusual in your log?
