### ISSUE TITLE
Pickup item make me CRASH

### ISSUE THREAD

**Issue by Zack7292** [transfarmer/adventure-items#4]
when i try to pick up item, your mod (i try removing it and it wasn't crashing) make my game crash
here a crash log with my full mod list: https://paste.dimdev.org/amecukekug.mccrash

**Comment by nnym** [comment]
I made some changes that I believe to have fixed the issue. I'll upload them to CurseForge now.

**Comment by Zack7292** [comment]
i can confirm it is fix :)
