### ISSUE TITLE
I got this bug between Ice and fire and Soulbound armory

### ISSUE THREAD

**Issue by Novastrikebugreporter** [transfarmer/adventure-items#5]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020-02-18 10:57:21 COT
Description: Ticking entity

java.lang.NullPointerException
    at transfarmer.soulboundarmory.capability.tool.SoulTool.getDatum(SoulTool.java:58)
    at transfarmer.soulboundarmory.event.ToolEventSubscriber.onPlayerDrops(ToolEventSubscriber.java:92)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_682_ToolEventSubscriber_onPlayerDrops_PlayerDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.entity.player.EntityPlayerMP.onDeath(EntityPlayerMP.java:510)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023)
    at net.minecraft.entity.player.EntityPlayer.attackEntityFrom(EntityPlayer.java:1038)
    at net.minecraft.entity.player.EntityPlayerMP.attackEntityFrom(EntityPlayerMP.java:645)
    at com.github.alexthe666.iceandfire.entity.IaFDragonDestructionManager.destroyAreaFire(IaFDragonDestructionManager.java:69)
    at com.github.alexthe666.iceandfire.entity.EntityFireDragon.stimulateFire(EntityFireDragon.java:386)
    at com.github.alexthe666.iceandfire.entity.EntityFireDragon.shootFireAtMob(EntityFireDragon.java:298)
    at com.github.alexthe666.iceandfire.entity.EntityFireDragon.onLivingUpdate(EntityFireDragon.java:177)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at com.github.alexthe666.iceandfire.entity.EntityDragonBase.onUpdate(EntityDragonBase.java:1408)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zbc000(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: iceandfire:firedragon (com.github.alexthe666.iceandfire.entity.EntityFireDragon)
  Entity ID: 20134
  Entity Name: Dragón de Fuego
  Entity's Exact location: -113.17, 63.00, 96.52
  Entity's Block location: World: (-114,63,96), Chunk: (at 14,3,0 in -8,6; contains blocks -128,0,96 to -113,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Entity's Momentum: -0.06, -0.08, 0.05
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:679,Attributes:[{Base:-2.0d,Name:"tc.mobmod"},{Base:0.0d,Name:"tc.mobmodtaint"},{Base:1.0d,Name:"potioncore.projectileDamage"},{Base:1.0d,Name:"potioncore.magicDamage"},{Base:1.0d,Name:"potioncore.jumpHeight"},{Base:1.0d,Name:"potioncore.damageResistance"},{Base:0.0d,Name:"potioncore.magicShielding"},{Base:346.0d,Modifiers:[{UUIDMost:-4557935957806527035L,UUIDLeast:-4950522221421205810L,Amount:3.0517578125E-4d,Operation:1,Name:"ScalingHealth.HealthModifier"}],Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.3200000059604645d,Name:"generic.movementSpeed"},{Base:14.92d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:128.0d,Name:"generic.followRange"},{Base:13.0d,Modifiers:[{UUIDMost:-3218372695593237220L,UUIDLeast:-8743736172551149415L,Amount:0.009093133732676506d,Operation:0,Name:"ScalingHealth.DamageModifier"}],Name:"generic.attackDamage"}],Invulnerable:0b,Gender:1b,AbsorptionAmount:0.0f,AttackDecision:0b,Hovering:0b,FallDistance:0.0f,InLove:0,FireBreathing:1b,ForgeCaps:{"tinkertoolleveling:entityxp":[],"thebetweenlands:entity_gems":{gems:[]},"cqrepoured:armor_turtle":0,"cqrepoured:armor_slime":0,"thebetweenlands:custom_step_sound":{},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:1},"Ice And Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"ancientwarfarestructure:respawn_data":{},"thebetweenlands:puppet":{ticks:0,guard:0b,recruitmentCost:0,stay:0b},"twilightforest:cap_shield":{permshields:0,tempshields:0},"everlastingabilities:org.cyclops.everlastingabilities.api.capability.imutableabilitystore":[],"thebetweenlands:equipment":{amuletSlots:1},"lycanitesmobs:iextendedentity":{}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Items:[],ModelDead:0b,Leashed:0b,Air:300s,DeadProg:0.0f,HandItems:[{},{}],AgeTicks:2040000,HasHomePosition:0b,Variant:2,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],OwnerUUID:"",Flying:0b,Tackle:0b,Pos:[-113.17128402248257d,63.0d,96.51941963954111d],CanPickUpLoot:0b,HurtTime:0s,ForgeData:{"scalinghealth:difficulty":0s,"Potion Core - Health Fix":339.0456f,thebetweenlands.has_no_equipment:1b,"Potion Core - Jump Boost Updated":1b},Sitting:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,Hunger:0,DeathTime:0s,AgingDisabled:1b,Age:0,Motion:[-0.05611157008927039d,-0.0784000015258789d,0.04568721554773127d],UUIDLeast:-8031399410487353489L,Health:339.0456f,LeftHanded:0b,OnGround:1b,Dimension:0,DeathStage:0,Rotation:[57.371536f,24.865253f],UpdateBlocked:0b,UUIDMost:5807960027179795489L,Sleeping:0b,Command:0,Fire:1s,ArmorItems:[{},{},{},{}]}

-- Affected level --
  Level name: Mundo nuevo
  All players: 1 total; [EntityPlayerMP['Cardexz'/19908, l='Mundo nuevo', x=-118.36, y=64.00, z=99.83]]
  Chunk stats: ServerChunkCache: 408 Drop: 0
  Level seed: -6501949156903156609
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-4,64,256), Chunk: (at 12,4,0 in -1,16; contains blocks -16,0,256 to -1,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 10921 game time, 10921 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 33878 (now: false), thunder time: 46005 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3817370936 bytes (3640 MB) / 5234491392 bytes (4992 MB) up to 5301600256 bytes (5056 MB)
  JVM Flags: 8 total; -Xmn128M -Xmx5039M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 74 mods loaded, 74 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version                  | Source                                             | Signature                                |
       |:------ |:------------------------ |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                      | 9.42                     | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                      | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | forge                    | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | ivtoolkit                | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCHIJA | jei                      | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                          | None                                     |
       | LCHIJA | abyssalcraft             | 1.9.16                   | AbyssalCraft-1.12.2-1.9.16.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | actuallyadditions        | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151-2.jar                | None                                     |
       | LCHIJA | codechickenlib           | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ancientwarfare           | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
       | LCHIJA | ebwizardry               | 4.2.8                    | ElectroblobsWizardry-4.2.8-MC1.12.2.jar            | None                                     |
       | LCHIJA | arcane_essentials        | 1.0                      | Arcane+Essentials-1.0.0-alpha-5.jar                | None                                     |
       | LCHIJA | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | betternether             | 0.1.8.6                  | betternether-0.1.8.6.jar                           | None                                     |
       | LCHIJA | bookshelf                | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | thaumcraft               | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | LCHIJA | botania                  | r1.10-363                | Botania+r1.10-363.jar                              | None                                     |
       | LCHIJA | llibrary                 | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | cqrepoured               | 1.9.0A                   | ChocolateQuestRepoured-1.12.2-1.9.0A.jar           | None                                     |
       | LCHIJA | craftstudioapi           | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJA | cyclopscore              | 1.6.1                    | CyclopsCore-1.12.2-1.6.1.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | eplus                    | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | everlastingabilities     | 1.5.2                    | EverlastingAbilities-1.12.2-1.5.2.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | potioncore               | 1.8_for_1.12.2           | PotionCore-1.8_for_1.12.2.jar                      | None                                     |
       | LCHIJA | eapotioncore             | 1.0.2                    | EverlastingAbilities-PotionCore-1.12.2-1.0.2.jar   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | expandableinventory      | 1.4.0                    | ExpandableInventory-1.12.2-1.4.0.jar               | None                                     |
       | LCHIJA | mantle                   | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | twilightforest           | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | tconstruct               | 1.12.2-2.13.0.171        | TConstruct-1.12.2-2.13.0.171.jar                   | None                                     |
       | LCHIJA | extrabotany              | 57                       | ExtraBotany-r1.1-57.jar                            | None                                     |
       | LCHIJA | extra_spells             | 1.1.4                    | ExtraSpells-1.12.2-1.1.4.jar                       | None                                     |
       | LCHIJA | foamfix                  | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCHIJA | forgelin                 | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJA | grimoireofgaia           | 1.7.1                    | GrimoireOfGaia3-1.12.2-1.7.1.jar                   | None                                     |
       | LCHIJA | hammercore               | 2.0.6.13                 | HammerCore-1.12.2-2.0.6.13.jar                     | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | helpfixer                | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                        | None                                     |
       | LCHIJA | heroicarmory             | 1.1.3                    | heroicarmory-1.2.0.jar                             | None                                     |
       | LCHIJA | iceandfire               | 1.8.4                    | iceandfire-1.8.4.jar                               | None                                     |
       | LCHIJA | improvableskills         | 65r                      | ImprovableSkills-1.12.2-65r.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | journeymap               | 1.12.2-5.5.9             | journeymap-1.12.2-5.5.9.jar                        | None                                     |
       | LCHIJA | libraryex                | 1.0.12                   | LibraryEx-1.12.2-1.0.12.jar                        | None                                     |
       | LCHIJA | liquid_luck              | 1.2                      | liquidluck-1.2.jar                                 | None                                     |
       | LCHIJA | lycanitesmobs            | 2.0.6.4 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.6.4.jar                   | None                                     |
       | LCHIJA | mjrlegendslib            | 1.12.2-1.1.9             | MJRLegendsLib-1.12.2-1.1.9.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | mowziesmobs              | 1.5.4                    | mowziesmobs-1.5.4.jar                              | None                                     |
       | LCHIJA | mutantbeasts             | 1.12.2-0.6.2             | MutantBeasts-1.12.2-0.6.2.jar                      | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LCHIJA | netherex                 | 2.0.15                   | NetherEx-1.12.2-2.0.15.jar                         | None                                     |
       | LCHIJA | nei                      | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | oxygen_core              | 0.10.0                   | oxygen-core-1.12.2-0.10.0.jar                      | 503a793335572ddd78512349bd8048f536a62fdb |
       | LCHIJA | oxygen_merchants         | 0.10.0                   | oxygen-merchants-1.12.2-0.10.0.jar                 | 503a793335572ddd78512349bd8048f536a62fdb |
       | LCHIJA | patchouli                | 1.0-20                   | Patchouli-1.0-20.jar                               | None                                     |
       | LCHIJA | reccomplex               | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | LCHIJA | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHIJA | subcommonlib             | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.2b.jar            | None                                     |
       | LCHIJA | rpginventory             | 1.12.2                   | rpginventory-1.12-5.3.0.0.jar                      | None                                     |
       | LCHIJA | silentlib                | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                    | None                                     |
       | LCHIJA | scalinghealth            | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar                | None                                     |
       | LCHIJA | scalingwealth            | 1.0.1                    | ScalingWealth-1.0.1.jar                            | None                                     |
       | LCHIJA | soulboundarmory          | 2.0.2-beta               | soulboundarmory-2.0.2-beta.jar                     | None                                     |
       | LCHIJA | spartanshields           | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
       | LCHIJA | tc6aspects4jei           | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                          | None                                     |
       | LCHIJA | thaumicjei               | 1.2.1                    | ThaumicJEI-1.12.2-1.5.3-20.jar                     | None                                     |
       | LCHIJA | tinkertoolleveling       | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar                | None                                     |
       | LCHIJA | torohealthmod            | 1.12.2-11                | torohealth-1.12.2-11.jar                           | None                                     |
       | LCHIJA | buildhelper              | 1.0.4.1                  | torojimaBuildHelper-1.0.4.1.jar                    | None                                     |
       | LCHIJA | travellersbackpack       | 1.0.22.22                | TravellersBackpack-1.12.2-1.0.22.22.jar            | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | waystones                | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                         | None                                     |
       | LCHIJA | thebetweenlands          | 3.5.6                    | TheBetweenlands-3.5.6-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      iceandfire (iceandfire-1.8.4.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      HCASM (HammerCore-1.12.2-2.0.6.13.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  HammerCore Debug Information: Dependent Mods:
                                    -Improvable Skills (improvableskills) @65r
  Suspected Mods: soulbound armory (soulboundarmory), Ice and Fire (iceandfire)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Cardexz'/19908, l='Mundo nuevo', x=-118.36, y=64.00, z=99.83]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by nnym** [comment]
This problem is entirely on my side. I seem to have fixed it; an update should be available on CurseForge soon.
