### ISSUE TITLE
Crash with the pickaxe

### ISSUE THREAD

**Issue by Zack7292** [transfarmer/adventure-items#8]
when i mine a block with the pickaxe AND A HASTE lvl 255 effect my game crash
the crash is the same https://pastebin.com/GpB2AEcX 
 sorry for missing this information i've forgot it

**Comment by nnym** [comment]
Does your pickaxe have additional data that affect its tooltip (things like enchantments and attributes like knockback and attack damage)?

**Comment by Zack7292** [comment]
no i just took one from the inventory that's it

**Comment by nnym** [comment]
I was finally able to reproduce the bug and I seem to have fixed it. Try version 2.1.1 and please close the issue if it fixes the bug.

**Comment by nnym** [comment]
Never mind that. It happened to me only once, and most of the time the "fix" makes the tooltip look strange. I'll revert the change for now.

**Comment by Zack7292** [comment]
Ok

**Comment by Zack7292** [comment]
it is fix for me!
